/** A podcast generated by the current user. */
export interface Podcast {
  id: string;
  original_filename: string;
  status: string;
  audio_url: string | null;
  created_at: string;
}

/** A public podcast from another user (Discover feed). */
export interface PublicPodcast {
  id: string;
  title: string;
  creator: string;
  niche: string;
  duration: string;
  plays: number;
  created_at: string;
}

/** Explore category definition. */
export interface Category {
  name: string;
  icon: string;
  color: string;
}
